version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'no-changelog'
    cooldown:
      default-days: 7
    groups:
      non-major-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'uv'
    directory: /
    schedule:
      interval: daily
    labels:
      - 'no-changelog'
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    versioning-strategy: increase-if-necessary
    groups:
      python-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      python-major:
        patterns:
          - '*'
        update-types:
          - 'major'

  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'no-changelog'
    cooldown:
      default-days: 7
      semver-major-days: 30
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
      npm-major:
        patterns:
          - '*'
        update-types:
          - 'major'
    ignore:
      - dependency-name: '@types/vscode'
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
